#!/bin/sh
./halite -q -r "java ModifiedBot GABot_F1_0" "java ModifiedBot GABot_F1_1" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_0" "java ModifiedBot GABot_F1_1" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_2" "java ModifiedBot GABot_F1_3" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_2" "java ModifiedBot GABot_F1_3" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_4" "java ModifiedBot GABot_F1_5" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_4" "java ModifiedBot GABot_F1_5" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_6" "java ModifiedBot GABot_F1_7" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_6" "java ModifiedBot GABot_F1_7" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_8" "java ModifiedBot GABot_F1_9" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_8" "java ModifiedBot GABot_F1_9" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_10" "java ModifiedBot GABot_F1_11" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_10" "java ModifiedBot GABot_F1_11" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_12" "java ModifiedBot GABot_F1_13" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_12" "java ModifiedBot GABot_F1_13" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_14" "java ModifiedBot GABot_F1_15" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_14" "java ModifiedBot GABot_F1_15" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_0" "java ModifiedBot GABot_F1_1" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_0" "java ModifiedBot GABot_F1_1" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_2" "java ModifiedBot GABot_F1_3" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_2" "java ModifiedBot GABot_F1_3" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_4" "java ModifiedBot GABot_F1_5" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_4" "java ModifiedBot GABot_F1_5" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_6" "java ModifiedBot GABot_F1_7" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_6" "java ModifiedBot GABot_F1_7" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_8" "java ModifiedBot GABot_F1_9" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_8" "java ModifiedBot GABot_F1_9" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_10" "java ModifiedBot GABot_F1_11" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_10" "java ModifiedBot GABot_F1_11" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_12" "java ModifiedBot GABot_F1_13" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_12" "java ModifiedBot GABot_F1_13" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
./halite -q -r "java ModifiedBot GABot_F1_14" "java ModifiedBot GABot_F1_15" "java ModifiedBot GABot_C3_0" "java ModifiedBot GABot_D3_0"
./halite -q -r "java ModifiedBot GABot_F1_14" "java ModifiedBot GABot_F1_15" "java ModifiedBot GABot_E3_0" "java ModifiedBot GABot_E3_0"
java genAlgo/TournamentSelector
source configs/matches.sh
