#!/bin/sh
./halite -q "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@1"
./halite -q "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@5"
./halite -q "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@6"
./halite -q "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@7"
./halite -q "java ModifiedBot GABot_@0" "java ModifiedBot GABot_A0"
./halite -q "java ModifiedBot GABot_@0" "java ModifiedBot GABot_B3"
./halite -q "java ModifiedBot GABot_@0" "java ModifiedBot GABot_C2"
./halite -q "java ModifiedBot GABot_@0" "java ModifiedBot GABot_D0"
./halite -q "java ModifiedBot GABot_@0" "java MBotA"
./halite -q "java ModifiedBot GABot_@0" "java MBotB"
./halite -q "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@2" "java ModifiedBot GABot_@3" "java ModifiedBot GABot_@4"
./halite -q "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0"
./halite -q "java ModifiedBot GABot_@1" "java ModifiedBot GABot_@0"
./halite -q "java ModifiedBot GABot_@1" "java ModifiedBot GABot_@2"
./halite -q "java ModifiedBot GABot_@1" "java ModifiedBot GABot_@6"
./halite -q "java ModifiedBot GABot_@1" "java ModifiedBot GABot_@7"
./halite -q "java ModifiedBot GABot_@1" "java ModifiedBot GABot_A0"
./halite -q "java ModifiedBot GABot_@1" "java ModifiedBot GABot_B3"
./halite -q "java ModifiedBot GABot_@1" "java ModifiedBot GABot_C2"
./halite -q "java ModifiedBot GABot_@1" "java ModifiedBot GABot_D0"
./halite -q "java ModifiedBot GABot_@1" "java MBotA"
./halite -q "java ModifiedBot GABot_@1" "java MBotB"
./halite -q "java ModifiedBot GABot_@1" "java ModifiedBot GABot_@3" "java ModifiedBot GABot_@4" "java ModifiedBot GABot_@5"
./halite -q "java ModifiedBot GABot_@1" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0"
./halite -q "java ModifiedBot GABot_@2" "java ModifiedBot GABot_@0"
./halite -q "java ModifiedBot GABot_@2" "java ModifiedBot GABot_@1"
./halite -q "java ModifiedBot GABot_@2" "java ModifiedBot GABot_@3"
./halite -q "java ModifiedBot GABot_@2" "java ModifiedBot GABot_@7"
./halite -q "java ModifiedBot GABot_@2" "java ModifiedBot GABot_A0"
./halite -q "java ModifiedBot GABot_@2" "java ModifiedBot GABot_B3"
./halite -q "java ModifiedBot GABot_@2" "java ModifiedBot GABot_C2"
./halite -q "java ModifiedBot GABot_@2" "java ModifiedBot GABot_D0"
./halite -q "java ModifiedBot GABot_@2" "java MBotA"
./halite -q "java ModifiedBot GABot_@2" "java MBotB"
./halite -q "java ModifiedBot GABot_@2" "java ModifiedBot GABot_@4" "java ModifiedBot GABot_@5" "java ModifiedBot GABot_@6"
./halite -q "java ModifiedBot GABot_@2" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0"
./halite -q "java ModifiedBot GABot_@3" "java ModifiedBot GABot_@0"
./halite -q "java ModifiedBot GABot_@3" "java ModifiedBot GABot_@1"
./halite -q "java ModifiedBot GABot_@3" "java ModifiedBot GABot_@2"
./halite -q "java ModifiedBot GABot_@3" "java ModifiedBot GABot_@4"
./halite -q "java ModifiedBot GABot_@3" "java ModifiedBot GABot_A0"
./halite -q "java ModifiedBot GABot_@3" "java ModifiedBot GABot_B3"
./halite -q "java ModifiedBot GABot_@3" "java ModifiedBot GABot_C2"
./halite -q "java ModifiedBot GABot_@3" "java ModifiedBot GABot_D0"
./halite -q "java ModifiedBot GABot_@3" "java MBotA"
./halite -q "java ModifiedBot GABot_@3" "java MBotB"
./halite -q "java ModifiedBot GABot_@3" "java ModifiedBot GABot_@5" "java ModifiedBot GABot_@6" "java ModifiedBot GABot_@7"
./halite -q "java ModifiedBot GABot_@3" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0"
./halite -q "java ModifiedBot GABot_@4" "java ModifiedBot GABot_@1"
./halite -q "java ModifiedBot GABot_@4" "java ModifiedBot GABot_@2"
./halite -q "java ModifiedBot GABot_@4" "java ModifiedBot GABot_@3"
./halite -q "java ModifiedBot GABot_@4" "java ModifiedBot GABot_@5"
./halite -q "java ModifiedBot GABot_@4" "java ModifiedBot GABot_A0"
./halite -q "java ModifiedBot GABot_@4" "java ModifiedBot GABot_B3"
./halite -q "java ModifiedBot GABot_@4" "java ModifiedBot GABot_C2"
./halite -q "java ModifiedBot GABot_@4" "java ModifiedBot GABot_D0"
./halite -q "java ModifiedBot GABot_@4" "java MBotA"
./halite -q "java ModifiedBot GABot_@4" "java MBotB"
./halite -q "java ModifiedBot GABot_@4" "java ModifiedBot GABot_@6" "java ModifiedBot GABot_@7" "java ModifiedBot GABot_@0"
./halite -q "java ModifiedBot GABot_@4" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0"
./halite -q "java ModifiedBot GABot_@5" "java ModifiedBot GABot_@2"
./halite -q "java ModifiedBot GABot_@5" "java ModifiedBot GABot_@3"
./halite -q "java ModifiedBot GABot_@5" "java ModifiedBot GABot_@4"
./halite -q "java ModifiedBot GABot_@5" "java ModifiedBot GABot_@6"
./halite -q "java ModifiedBot GABot_@5" "java ModifiedBot GABot_A0"
./halite -q "java ModifiedBot GABot_@5" "java ModifiedBot GABot_B3"
./halite -q "java ModifiedBot GABot_@5" "java ModifiedBot GABot_C2"
./halite -q "java ModifiedBot GABot_@5" "java ModifiedBot GABot_D0"
./halite -q "java ModifiedBot GABot_@5" "java MBotA"
./halite -q "java ModifiedBot GABot_@5" "java MBotB"
./halite -q "java ModifiedBot GABot_@5" "java ModifiedBot GABot_@7" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@1"
./halite -q "java ModifiedBot GABot_@5" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0"
./halite -q "java ModifiedBot GABot_@6" "java ModifiedBot GABot_@3"
./halite -q "java ModifiedBot GABot_@6" "java ModifiedBot GABot_@4"
./halite -q "java ModifiedBot GABot_@6" "java ModifiedBot GABot_@5"
./halite -q "java ModifiedBot GABot_@6" "java ModifiedBot GABot_@7"
./halite -q "java ModifiedBot GABot_@6" "java ModifiedBot GABot_A0"
./halite -q "java ModifiedBot GABot_@6" "java ModifiedBot GABot_B3"
./halite -q "java ModifiedBot GABot_@6" "java ModifiedBot GABot_C2"
./halite -q "java ModifiedBot GABot_@6" "java ModifiedBot GABot_D0"
./halite -q "java ModifiedBot GABot_@6" "java MBotA"
./halite -q "java ModifiedBot GABot_@6" "java MBotB"
./halite -q "java ModifiedBot GABot_@6" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@1" "java ModifiedBot GABot_@2"
./halite -q "java ModifiedBot GABot_@6" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0"
./halite -q "java ModifiedBot GABot_@7" "java ModifiedBot GABot_@0"
./halite -q "java ModifiedBot GABot_@7" "java ModifiedBot GABot_@4"
./halite -q "java ModifiedBot GABot_@7" "java ModifiedBot GABot_@5"
./halite -q "java ModifiedBot GABot_@7" "java ModifiedBot GABot_@6"
./halite -q "java ModifiedBot GABot_@7" "java ModifiedBot GABot_A0"
./halite -q "java ModifiedBot GABot_@7" "java ModifiedBot GABot_B3"
./halite -q "java ModifiedBot GABot_@7" "java ModifiedBot GABot_C2"
./halite -q "java ModifiedBot GABot_@7" "java ModifiedBot GABot_D0"
./halite -q "java ModifiedBot GABot_@7" "java MBotA"
./halite -q "java ModifiedBot GABot_@7" "java MBotB"
./halite -q "java ModifiedBot GABot_@7" "java ModifiedBot GABot_@1" "java ModifiedBot GABot_@2" "java ModifiedBot GABot_@3"
./halite -q "java ModifiedBot GABot_@7" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0" "java ModifiedBot GABot_@0"
